package pl.oazapraga.oremus.app

enum class ValidationIssue {
    DAYS_RANGE_END_DATE_BEFORE_DAYS_RANGE_START_DATE,
    CREATING_REFLECTION_BEGINNING_DATE_BEFORE_CREATING_REFLECTION_END_DATE,
    MISSING_NAME,
    DATES_OVERLAPS_EXISTING_RANGE,
    NO_EDITION_EXISTS,
    OUT_OF_EDITION_CREATE_REFLECTION_PERIOD
}
